[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.7"
paho-mqtt = "0.13.2"
tokio = { version = "1.45.1", features = ["full"] }
